[alias]
perf = "flamegraph --root --bin performance-test"
"perf:debug" = "flamegraph --root --dev --bin performance-test"
"test:watch" = ["watch", "-x", "test --lib"]
"test:all" = "test --release"

[profile.release]
debug = true
